/* SPDX-License-Identifier: GPL-2.0-only */
#ifndef TOUCH_PROTOCOL_H
#define TOUCH_PROTOCOL_H

#define TOUCH_I2C_ADDRESS 0x2a
#define TOUCH_PROTOCOL_VERSION 1
#define TOUCH_FRAME_SIZE 64
#define TOUCH_CHANNEL_COUNT 6
#define TOUCH_POSITION_MAX 1023
#define TOUCH_POSITION_INVALID 0xffff
#define TOUCH_REG_FRAME 0x00
#define TOUCH_REG_ACK 0x80

#define TOUCH_CAP_KEYS 0x01
#define TOUCH_CAP_POSITION 0x02
#define TOUCH_CAP_GESTURES 0x04
#define TOUCH_CAP_DIAGNOSTICS 0x08
#define TOUCH_CAP_IRQ 0x10
#define TOUCH_STATUS_READY 0x01
#define TOUCH_STATUS_TOUCH 0x02
#define TOUCH_STATUS_POSITION_VALID 0x04
#define TOUCH_STATUS_MULTI 0x08

#define TOUCH_OFF_CAPS 4
#define TOUCH_OFF_STATUS 5
#define TOUCH_OFF_CHANNELS 6
#define TOUCH_OFF_PEAK 7
#define TOUCH_OFF_SEQUENCE 8
#define TOUCH_OFF_UPTIME 12
#define TOUCH_OFF_KEY_MASK 16
#define TOUCH_OFF_POSITION 18
#define TOUCH_OFF_NEGATIVE_SWIPES 20
#define TOUCH_OFF_POSITIVE_SWIPES 24
#define TOUCH_OFF_GESTURE_TIME 28
#define TOUCH_OFF_STRENGTH 32
#define TOUCH_OFF_BASELINE 44
#define TOUCH_OFF_CONTACT_COUNT 56
#define TOUCH_OFF_SEQUENCE_END 60

#endif
